openapi: 3.0.0
info:
  version: "1.0.0"
  title: Kubera initial API
  description: >
    This is the initial API design for Kubera.
    It was made using an HTTP-RPC style, following the requirements defined in [this document](https://docs.google.com/a/omise.co/document/d/1jy7CDpkkVcCoMy9Dp3GFEOzcMYPfNhpvK8dJH9L6q-E/edit?usp=sharing).
    Two kinds of endpoints can be found in this document: the server endpoints and the client (mobile wallet) endpoints. Basically, all API calls that modify the database need to be done from the server for security purposes using an `ACCESS_KEY`/`SECRET_KEY` combo. Retrieval calls can be made from the client (considered unsafe, 'never trust the client') using an API key (which can be disabled from the admin panel) and an access token. All API calls will be authorized using the 'Authorization' HTTP header using the following format: For server -> `Authorization=OMGServer Base64(access_key:secret_key)`, for client -> `Authorization=OMGClient Base64(api_key:authentication_token)`. Error codes are defined in the following [doc](https://docs.google.com/a/omise.co/spreadsheets/d/1yq5IIoXQYV_ZlUVejAnhB8lVra2rxm56EnyjfMqFcU8/edit?usp=sharing). The API will always return a `200` HTTP status except if there was a server error, in that case, `500` will be returned.
  contact:
    name: OmiseGO
    email: mederic@omise.co
  license:
    name: License To define
    url: 'https://omg.omise.co/'
tags:
  - name: User
    description: These are the endpoints related to the user resource. A user is an entity uniquely identified by its provider_user_id which is the user id in the provider database.
  - name: Balance
    description: These are the endpoints related to the balances of a specific user. Balances are the representation of the amount of each token a user owns.
  - name: Setting
    description: These are the endpoints related to the global settings of the wallet.
paths:
  ############################
  #           USERS          #
  ############################
  # Endpoint to create a user.
  /user.create:
    post:
      tags:
        - User
      summary: Server - Create a new user
      description: This is a server call only.
      operationId: user_create
      security:
        - ServerAuth: []
      requestBody:
        $ref: '#/components/requestBodies/UserBody'
      parameters:
        - $ref: "#/components/parameters/ServerAuthorizationHeader"
      responses:
        '200':
          $ref: "#/components/responses/UserResponse"
        '500':
          $ref: "#/components/responses/ServerError"
  # Endpoint to update a user.
  /user.update:
    post:
      tags:
        - User
      summary: Server - Update an existing user
      description: This is a server call only.
      operationId: user_update
      security:
        - ServerAuth: []
      parameters:
        - $ref: "#/components/parameters/ServerAuthorizationHeader"
      requestBody:
        $ref: '#/components/requestBodies/UserBody'
      responses:
        '200':
          $ref: "#/components/responses/UserResponse"
        '500':
          $ref: "#/components/responses/ServerError"
  # Endpoint to login a user.
  /user.login:
    post:
      tags:
        - User
      summary: Server - Login an existing user. The provider can call this to get an access token for a specific user.
      description: This is a server call only.
      operationId: user_login
      security:
        - ServerAuth: []
      parameters:
        - $ref: "#/components/parameters/ServerAuthorizationHeader"
      requestBody:
        $ref: '#/components/requestBodies/ProviderIdBody'
      responses:
        '200':
          $ref: "#/components/responses/AuthenticationTokenResponse"
        '500':
          $ref: "#/components/responses/ServerError"
  # Endpoint to get an existing user from its id
  /user.get:
    post:
      tags:
        - User
      summary: Server - Get an existing user. The provider can call this to get any user from its id.
      description: This is a server call only.
      operationId: user_get
      security:
        - ServerAuth: []
      parameters:
        - $ref: "#/components/parameters/ServerAuthorizationHeader"
      requestBody:
        $ref: '#/components/requestBodies/ProviderIdBody'
      responses:
        '200':
          $ref: "#/components/responses/UserResponse"
        '500':
          $ref: "#/components/responses/ServerError"
  # Endpoint to get an exising user from its authentication_token (get my user)
  /me.get:
    post:
      tags:
        - User
      summary: Client - Get the user corresponding to the provided authentication token.
      description: This is a wallet call.
      operationId: me_get
      security:
        - ClientAuth: []
      parameters:
        - $ref: "#/components/parameters/ClientAuthorizationHeader"
      responses:
        '200':
          $ref: "#/components/responses/UserResponse"
        '500':
          $ref: "#/components/responses/ServerError"
  ############################
  #          BALANCES        #
  ############################
  # Endpoint to get the balances of a specific user from its id
  /user.list_balances:
    post:
      tags:
        - Balance
      summary: Server - Get the balances of a user. The provider can call this to get the balances of any user from its id.
      description: This is a server call only.
      operationId: user_list_balances
      security:
        - ServerAuth: []
      parameters:
        - $ref: "#/components/parameters/ServerAuthorizationHeader"
      requestBody:
        $ref: '#/components/requestBodies/ProviderIdBody'
      responses:
        '200':
          $ref: "#/components/responses/BalancesResponse"
        '500':
          $ref: "#/components/responses/ServerError"
  #Endpoint to get the balances of a user from its authentication_token
  /me.list_balances:
    post:
      tags:
        - Balance
      summary: Client - Get the balances of a specific user. The client can call this to get the balances of the user corresponding to the authentication_token provided.
      description: This is a wallet call.
      operationId: me_list_balances
      security:
        - ClientAuth: []
      parameters:
        - $ref: "#/components/parameters/ClientAuthorizationHeader"
      responses:
        '200':
          $ref: "#/components/responses/BalancesResponse"
        '500':
          $ref: "#/components/responses/ServerError"
  #Endpoint to credit an existing user balance
  /user.credit_balance:
    post:
      tags:
        - Balance
      summary: Server - Credit the balance of a user. The provider can call this to credit the balance of an existing user corresponding to the provider_user_id provided.
      description: This is a server call only.
      operationId: user_credit_balance
      security:
        - ServerAuth: []
      parameters:
        - $ref: "#/components/parameters/ServerAuthorizationHeader"
      requestBody:
        $ref: '#/components/requestBodies/BalanceAdjustmentBody'
      responses:
        '200':
          $ref: "#/components/responses/BalanceResponse"
        '500':
          $ref: "#/components/responses/ServerError"
  # Endpoint to debit an exsiting user balance
  /user.debit_balance:
    post:
      tags:
        - Balance
      summary: Server - Debit the balance of a user. The provider can call this to debit the balance of an existing user corresponding to the provider_user_id provided.
      description: This is a server call only.
      operationId: user_debit_balance
      security:
        - ServerAuth: []
      parameters:
        - $ref: "#/components/parameters/ServerAuthorizationHeader"
      requestBody:
        $ref: '#/components/requestBodies/BalanceAdjustmentBody'
      responses:
        '200':
          $ref: "#/components/responses/BalanceResponse"
        '500':
          $ref: "#/components/responses/ServerError"
  ############################
  #          SETTINGS        #
  ############################
  # Endpoint to get global settings
  /me.get_settings:
    post:
      tags:
        - Setting
      summary: Client - Get the global settings.
      description: This is a wallet call.
      operationId: me_get_settings
      security:
        - ClientAuth: []
      parameters:
        - $ref: "#/components/parameters/ClientAuthorizationHeader"
      responses:
        '200':
          $ref: "#/components/responses/SettingResponse"
        '500':
          $ref: "#/components/responses/ServerError"

components:
  schemas:
    # Schema for a user object
    UserSchema:
      type: object
      properties:
        object:
          type: string
        id:
          type: string
        username:
          type: string
        provider_user_id:
          type: string
        metadata:
          type: object
      required:
        - object
        - id
        - username
        - provider_user_id
        - metadata
      example:
        object: "user"
        id: "cec34607-0761-4a59-8357-18963e42a1aa"
        provider_user_id: "wijf-fbancomw-dqwjudb"
        username: "thibault@omise.co"
        metadata: {"first_name": "Thibault", "last_name": "Denizet"}
    # Schema for an error object
    ErrorSchema:
      type: object
      properties:
        object:
          type: string
        code:
          type: string
        message:
          type: string
      required:
        - object
        - code
        - message
      example:
        object: error
        code: server_error
        message: Server error
    # Schema for a list object
    UnpaginatedListSchema:
      type: object
      properties:
        object:
          type: string
        data:
          type: array
      required:
        - object
        - data
      example:
        object: list
    # Schema for success response body
    BaseResponseSchema:
      type: object
      properties:
        version:
          type: string
        success:
          type: boolean
        data:
          type: object
      required:
        - version
        - success
        - data
      example:
        version: "1.0.0"
        success: true
    # Schema for error response body
    ErrorResponseSchema:
      allOf:
        - $ref: '#/components/schemas/BaseResponseSchema'
        - type: object
          properties:
            data:
              $ref: '#/components/schemas/ErrorSchema'
          required:
            - data
          example:
            success: false
            data:
              object: error
              code: server_error
              message: Server error
    # Schema for user response body
    UserResponseSchema:
      allOf:
      - $ref: '#/components/schemas/BaseResponseSchema'
      - type: object
        properties:
          data:
            type: object
            $ref: '#/components/schemas/UserSchema'
        required:
          - data
        example:
          data:
            object: "user"
            id: "cec34607-0761-4a59-8357-18963e42a1aa"
            provider_user_id: "wijf-fbancomw-dqwjudb"
            username: "thibault@omise.co"
            metadata: {"first_name": "Thibault", "last_name": "Denizet"}
    # Schema for authentication token object
    AuthenticationTokenSchema:
      type: object
      properties:
        object:
          type: string
        authentication_token:
          type: string
        expires_at:
          type: string
          format: date
      required:
        - object
        - authentication_token
        - expires_at
    # Schema for individual balance object
    BalanceSchema:
      type: object
      properties:
        object:
          type: string
        address:
          type: string
        symbol:
          type: string
        amount:
          type: integer
      required:
        - object
        - address
        - symbol
        - amount
      example:
        object: "balance"
        address: "XXXXXXXXXXXXXXXXXXXXX"
        symbol: "MNT"
        amount: 100
    # Schema for individual currency token object
    CurrencyTokenSchema:
      type: object
      properties:
        object:
          type: string
        symbol:
          type: string
        name:
          type: string
      required:
        - object
        - symbol
        - name
      example:
        object: "currency_token"
        symbol: "MNT"
        name: "Mint"
    # Schema for authentication token body response
    AuthenticationTokenResponse:
      allOf:
      - $ref: '#/components/schemas/BaseResponseSchema'
      - type: object
        properties:
          data:
            type: object
            $ref: '#/components/schemas/AuthenticationTokenSchema'
        required:
          - data
        example:
          data:
            object: "authentication_token"
            authentication_token: "azJRj09l7jvR8KhTqUs3"
            expires_at: "2020-10-10 00:00:00+00:00"
    # Schema for single balance body response
    BalanceResponse:
      allOf:
      - $ref: '#/components/schemas/BaseResponseSchema'
      - type: object
        properties:
          data:
            type: object
            $ref: '#/components/schemas/BalanceSchema'
        required:
          - data
        example:
          data:
            object: "balance"
            address: "XXXXXXXXXXXXXXXXXXXXX"
            symbol: "MNT"
            amount: 100
    # Schema for balance response body
    BalancesResponse:
      allOf:
      - $ref: '#/components/schemas/BaseResponseSchema'
      - type: object
        properties:
          data:
            type: object
            allOf:
              - $ref: '#/components/schemas/UnpaginatedListSchema'
              - type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/BalanceSchema'
        required:
        - data
        example:
          data:
            object: list
            data:
            - object: "balance"
              address: "XXXXXXXXXXXXXXXXXXXXX"
              symbol: "MNT"
              amount: 100
            - object: "balance"
              address: "XXXXXXXXXXXXXXXXXXXXX"
              symbol: "OMG"
              amount: 100
    # Schema for settings response body
    SettingResponse:
      allOf:
      - $ref: '#/components/schemas/BaseResponseSchema'
      - type: object
        properties:
          data:
            type: object
            properties:
              object:
                type: string
              tokens:
                type: array
                items:
                 $ref: '#/components/schemas/CurrencyTokenSchema'
            required:
              - object
              - tokens
        example:
          data:
            object: "setting"
            tokens:
              - object: "currency_token"
                symbol: "MNT"
                name: "Mint"
              - object: "currency_token"
                symbol: "OMG"
                name: "OmiseGO"
  requestBodies:
    # Body for a create / update user request
    UserBody:
      description: User object that needs to be created or updated
      required: true
      content:
        application/vnd.omisego.v1.0.0+json:
          schema:
            properties:
              provider_user_id:
                type: string
              username:
                type: string
              metadata:
                type: object
            required:
              - provider_user_id
              - username
              - metadata
            example:
              provider_user_id: "wijf-fbancomw-dqwjudb"
              username: "thibault@omise.co"
              metadata: {"first_name": "Thibault", "last_name": "Denizet"}
    # Body containing the provider user id
    ProviderIdBody:
      description: The provider id
      required: true
      content:
        application/vnd.omisego.v1.0.0+json:
          schema:
            properties:
              provider_user_id:
                type: string
            required:
              - provider_user_id
            example:
              provider_user_id: "wijf-fbancomw-dqwjudb"
    # Body for a credit / debit of a user's balance
    BalanceAdjustmentBody:
      description: Description of the desired adjustment
      required: true
      content:
        application/vnd.omisego.v1.0.0+json:
          schema:
            properties:
              provider_user_id:
                type: string
              symbol:
                type: string
              amount:
                type: integer
            required:
              - provider_user_id
              - symbol
              - amount
            example:
              provider_user_id: "wijf-fbancomw-dqwjudb"
              symbol: "MNT"
              amount: 100
  parameters:
    # Headers
    ServerAuthorizationHeader:
      in: header
      name: Authorization
      description: OMGServer Base64(access_key:secret_key)
      required: true
      schema:
        type: string
    ClientAuthorizationHeader:
      in: header
      name: Authorization
      description: OMGClient Base64(api_key:authentication_token)
      required: true
      schema:
        type: string
  securitySchemes:
    # Authentication for server calls
    ServerAuth:
      type: apiKey
      in: header
      name: Authorization
    # Authentication for client calls
    client_auth:
      type: apiKey
      in: header
      name: Authorization
  responses:
    # Response when there was a server error (should never happen)
    ServerError:
      description: Server error
      content:
        application/vnd.omisego.v1.0.0+json:
          schema:
            $ref: '#/components/schemas/ErrorResponseSchema'
    # User response
    UserResponse:
      description: User response
      content:
        application/vnd.omisego.v1.0.0+json:
          schema:
            $ref: '#/components/schemas/UserResponseSchema'
    # Authentication token response
    AuthenticationTokenResponse:
      description: Authentication token response
      content:
        application/vnd.omisego.v1.0.0+json:
          schema:
            $ref: '#/components/schemas/AuthenticationTokenResponse'
    # Balance response
    BalanceResponse:
      description: Balance response
      content:
        application/vnd.omisego.v1.0.0+json:
          schema:
            $ref: '#/components/schemas/BalanceResponse'
    # Balances response
    BalancesResponse:
      description: Balances response
      content:
        application/vnd.omisego.v1.0.0+json:
          schema:
            $ref: '#/components/schemas/BalancesResponse'
    # Setting response
    SettingResponse:
      description: Setting response
      content:
        application/vnd.omisego.v1.0.0+json:
          schema:
            $ref: '#/components/schemas/SettingResponse'
